### ISSUE TITLE
workflowscheduler fails when running via supervisor

### ISSUE THREAD

**Issue by bpatzak** [mupif/mupifDB#10]
The recent changes in workflowscheduler lead to strange behavior (can be replicated in test container)
When workflowscheduler is run from command line as 
MUPIF_NS=172.24.1.1:10000 python3 workflowscheduler.py
everything works fine

When workflowscheduler is started using supervisor, the mupif interface fails (https://mupif.org/test/ page does not work)
It could be because the supervisor config for mupifdb-scheduler does not set the MUPIF_NS variable, so that the monitor could not register itself to nameserver.

**Comment by bpatzak** [comment]
The problem has been solved. Under supervisor, the workflowscheduler  runs under mupif user, while in command line under root. It could not write to persistent/scheduler-stat.json file (which was owned by root). Fixing permission on persistent/scheduler-stat.json solved the problem.

**Comment by eudoxos** [comment]
Glad  that it is solved. For the records, I verified now with supervisor that environment variables from Docker (and in supervisor) are passed to the services; `MUPIF_NS` is one of them, https://github.com/mupif/infrastructure-docker/blob/d8377d4cebf06fabd4508ecad47fa162efd75e23/Dockerfile#L33 , the values are set in `mech2018:/root/mupif-networks/musicode/container.yml`.
