### ISSUE TITLE
Accessing REST API endpoint from JS (client-side)

### ISSUE THREAD

**Issue by eudoxos** [mupif/mupifDB#5]
We use `MUPIFDB_REST_SERVER` to know where the REST server is running. This is used in the python code (that is, server-side).
https://github.com/mupif/mupifDB/blob/38e41ddbdbf1ec31900f85b3bb655cf7f46a59b9/webapi/index.py#L26

In the stats page, the REST server should be queried for updates on execution count. That code is running on the client, thus `MUPIFDB_REST_SERVER` might not be correct (even if passed):
https://github.com/mupif/mupifDB/blob/38e41ddbdbf1ec31900f85b3bb655cf7f46a59b9/webapi/templates/stat.html#L103

Proposed solutions: 

(a) Use `MUPIF_NS` in `index.py`, query the mupifDB REST server from the nameserver itself (won't be loopback); then use it in both server-side and client-side code.

(b) Pass `MUPIFDB_REST_SERVER` as `render_template` parameter; in that case, it would have to be non-loopback address, thus different for each VPN. It could be set from the supervisor as env var as `http://$MUPIF_NS_HOST:5555`.

**Comment by eudoxos** [comment]
Now with solution (b) in place, I am getting this:
![image](https://user-images.githubusercontent.com/1029876/147874257-d8f8915e-c985-4d9b-a2a2-77d26874978d.png)

**Comment by bpatzak** [comment]
For me the following works (using Deema VPN):
$ curl  http://172.23.1.1:5000/main?action=get_status

the REST API is (self) documented here: http://172.23.1.1:5000/help

**Comment by eudoxos** [comment]
I just change `json.result[0]` to `json.result` (in https://github.com/mupif/mupifDB/commit/d5fb3539b30a71519769768f1ad78c305afc2edb) and it seems to be working in the test VPN. Does the change make sense? The API is not returning an array.

**Comment by stanislavsulc** [comment]
Yes, as it returns the status info, it is not meant to be an array. I hope that it is ok.
