### ISSUE TITLE
REST API get_execution_inputs/outputs response lacks TypeID attribute

### ISSUE THREAD

**Issue by bpatzak** [mupif/mupifDB#6]
The response for the endpoints main?action=get_execution_inputs and main?action=get_execution_outputs does not contain TypeID field, so the physical meaning of i/o parameter could not be determined. 
(see http://[172.24.1.1:5000/main?action=get_execution_outputs&id=62064e3a62ec0e75f23c552b](http://172.24.1.1:5000/main?action=get_execution_outputs&id=62064e3a62ec0e75f23c552b for illustration)

**Comment by stanislavsulc** [comment]
It should be fixed with commit https://github.com/mupif/mupifDB/commit/dae42485d2fd1f547ac691b2452179cddafa1227
